### ISSUE TITLE
Denizhan Dalgıç-Assignment1

### ISSUE THREAD

**Issue by devdalgic** [mertcanekiz/BLG252E_2020Spring#2]
https://github.com/Derrizah/Derrizah-DenizhanDalgic-BLG252-Assignment1

Thanks.

**Comment by mertcanekiz** [comment]
Absolute path yerine relative path kullanmanı öneririm. Şu an dosya adını değiştirmeden senin bilgisayarın dışında çalıştırmak mümkün değil çünkü. #3 te arkadaşının nasıl yaptığına bakabilirsin.

Ya da integers.txt dosyasını `bin\Debug\netcoreapp2.1` içine kopyalarsan sadece dosya adını vererek açabilirsin:

```c#
...
var path = "integers.txt";
var fileStream = new FileStream(path, FileMode.Open, FileAccess.Read);
...
```
