### ISSUE TITLE
Arek Berç Gökdağ_Assignment1

### ISSUE THREAD

**Issue by ArekBerc** [mertcanekiz/BLG252E_2020Spring#3]
https://github.com/ArekBerc/BLG252E_exercises.git

İyi çalışmalar.

**Comment by ArekBerc** [comment]
Update: Bugfix

**Comment by mertcanekiz** [comment]
[Bu satırda](https://github.com/ArekBerc/BLG252E_exercises/blob/fa96a0bf2422c67e05d94266d2f736dfd55ae91e/assignment1/Program.cs#L17) backslash (`\`) kullandığın için Linux ve macOS'ta çalışmıyor. Bu eklemeyi manuel yapmak yerine `Path.Combine` kullanabilirsin:

```c#
path = Path.Combine(path, "integers.txt");
```

Bunun dışında bir sorun yok gibi duruyor, eline sağlık.

**Comment by ArekBerc** [comment]
Düzeltildi, teşekkürler.
