### ISSUE TITLE
Egemen Akar assignment 1

### ISSUE THREAD

**Issue by egemen-akar** [mertcanekiz/BLG252E_2020Spring#5]
https://github.com/egemen-akar/BLG252/tree/master/assignment1

**Comment by mertcanekiz** [comment]
Program çalışıyor, ancak kullandığın veri yapısı konusunda sanırım istenileni yanlış anlamışsın. .NET kütüphanesindeki `LinkedList` class'ını kullanmanız değil, kendi `LinkedList` yapınızı oluşturmanız isteniyor.

**Comment by egemen-akar** [comment]
düzelttim
